In [31]:
import numpy as np

In [11]:
a= np.ones(3)
print(a)

[1. 1. 1.]


In [13]:
b=np.zeros(3)
print(b)

[0. 0. 0.]


In [17]:
# "full" literally means: “fill the array completely with the value you give.”
# numpy signature: np.full(shape, fill_value, dtype=None, order='C')

import numpy as np

# 1D array of length 4, all elements are 9
a = np.full(4, 9)
print(a)  # Output: [9 9 9 9]

# 2D array of shape (2, 3), all elements are 0.5
b = np.full((2, 3), 0.5)
print(b)

[9 9 9 9]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [19]:
np.arange(2,3)

array([2])

In [37]:
# np.dot() is used in NumPy to multiply: Two numbers, Two vectors, A matrix and a vector, Two matrices
# 10*4 +50*5 = 290


import numpy as np 

a=np.array([10,50])
b=np.array([4,5])

np.dot(a,b)

290

In [43]:
# power function

import numpy as np

array1 = np.array([1, 2, 3, 5, 8])
array2 = np.array([3, 4, 5, 7, 8])

result_power = np.power(array1, array2)
print(result_power)

[       1       16      243    78125 16777216]


In [45]:
np.var(a,axis=None,dtype=None)

400.0

In [53]:
import numpy as np

numbers = [1, 5, 3, 8, 2]
print(np.max(numbers)) 

8


In [63]:
num=[1,2,3,4,5]

numpy_array=np.array(num)

In [69]:
array1 = np.array([1, 2, 3, 5, 8])
array2 = np.array([3, 4, 5, 7, 8])

Fin=np.vstack((array1,array2))

In [67]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3]})
print(df['A'].mean())

2.0


In [75]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])

c=np.concatenate((a,b),axis=0)
print("With axis 0:\n",c)

d=np.concatenate((a,b.T),axis=1)
print("With axis 1:\n",d)

With axis 0:
 [[1 2]
 [3 4]
 [5 6]]
With axis 1:
 [[1 2 5]
 [3 4 6]]


In [81]:
# vstack is used to define elements vertically.
#hstack for horizantally arranging elements.


import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.vstack((a,b))

print("After vstack:\n",c)

d=np.hstack((a,b))

print("After hstack:\n",d)

After vstack:
 [[1 2 3]
 [4 5 6]]
After hstack:
 [1 2 3 4 5 6]


In [120]:
# fliplr function is used to reverese the array left to righ 

import numpy as np
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[10,11,12]])

stacked=np.vstack((a,b))

print("after stacked:\n",stacked)

c=np.fliplr(stacked)

print(c)

d=np.flipud(stacked)

print(d)

after stacked:
 [[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
[[ 3  2  1]
 [ 9  8  7]
 [ 6  5  4]
 [12 11 10]]
[[10 11 12]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]]


In [124]:
# np.convolve is used to compute the moving average 

import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 4

weights = np.ones(window_size) / window_size
moving_avg = np.convolve(data, weights, mode='valid')

print(moving_avg)


# What is a Moving Average? It smooths data by averaging over a sliding window, For example:
#First 3 numbers: (1+2+3)/3 = 2

# Next 3: (2+3+4)/3 = 3

# And so on…

[2.5 3.5 4.5 5.5]


In [142]:
# np.array_split to split the array into as our wish size 

data = np.array([1, 2, 3, 4, 5, 6, 7])

arr1=np.array_split(data,3)

print(arr1)


ram=np.arange(8)   # takes values upto 7

arr2=np.array_split(ram,2)     # splits the data into 2 arrays 

arr3=np.array_split(ram,8)       # splits the date into 8 arrays 

print(arr2)
print(arr3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0]), array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7])]


In [165]:
# np.swapaxes(a,0,1)- swaps the rows into columns and cloumns into rows 

# 0,1 converts the 2 rows, 3columns into 3 rows, 2 columns


# np.swapaxes(arr, axis1, axis2) returns a view, not a copy.

# It's different from np.transpose() which can swap all axes at once.


import numpy as np

data = np.array([[1, 2, 3],     # Each row is a list
                 [6, 7, 8]])    # All rows are inside another list

arr1 = np.swapaxes(data, 0, 1)  # Swap rows and columns
print(arr1)

arr2 = np.transpose(data)       # Transpose (same as swapaxes for 2D)
print(arr2)


[[1 6]
 [2 7]
 [3 8]]
[[1 6]
 [2 7]
 [3 8]]


In [171]:
# changing the dimensions of an numpy array 

# if data=np.array([1,2,3,4,5,6,7,8]) it cant be converted into shape of (3,3) as only 8 elements 

data=np.array([1,2,3,4,5,6,7,8,9])

print(data.shape)

data.shape=(3,3)

print(" transformed shape:",data.shape)

print(data)


(9,)
 transformed shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [177]:
# padded function can be used to border an array  with zero's 

# pad width is no of layers & constant values means means value to be bordered with.

import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

# Pad with 1 layer of zeros around the array

padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(padded)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [179]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

# Pad with 1 layer of zeros around the array
padded = np.pad(arr, pad_width=2, mode='constant', constant_values=9)

print(padded)

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 1 2 9 9]
 [9 9 3 4 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [181]:
#no.ones means array with only ones 

data=np.ones((4,4))

arr1=np.pad(data,pad_width=2,mode='constant', constant_values=5)

print(arr1)

[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [183]:
data=np.arange(10,60)

print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


In [189]:
# to repeat the elements use np.char.multiply(arr,times like 5 or 6)
# np.char.join(' ',data) is used to keep spaces between the array data 

data=np.array(['I','Love','multiply'],dtype=str)

arr1=np.char.multiply(data,5)

arr2=np.char.join(' ',data)


print(arr1)

print(arr2)

['IIIII' 'LoveLoveLoveLoveLove' 'multiplymultiplymultiplymultiplymultiply']
['I' 'L o v e' 'm u l t i p l y']


In [193]:
data=np.array(['I','Love','multiply'],dtype=str)

arr1=np.char.upper(data)

arr2=np.char.lower(data)

arr3=np.char.capitalize(data)

arr4=np.char.title(data)

arr5=np.char.swapcase(data)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

['I' 'LOVE' 'MULTIPLY']
['i' 'love' 'multiply']
['I' 'Love' 'Multiply']
['I' 'Love' 'Multiply']
['i' 'lOVE' 'MULTIPLY']


In [195]:
# np.arange creates an array of elemts with same space 

data=np.arange(1,50,5)

print(data)

[ 1  6 11 16 21 26 31 36 41 46]


In [2]:
import numpy as np

In [6]:
#create an array

a=np.array([1,2,3,])

print("Array a:", a)


Array a: [1 2 3]


In [16]:
#evenly spaced array - use arange function and open brackets. no need of close brackets 

b=np.arange(0,10,2)

print("Array b:",b)

Array b: [0 2 4 6 8]


In [18]:
# Linearly spaced values refer to a sequence of numbers that are evenly distributed between a specified start and end point

c=np.linspace(0,10)
print(c)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [20]:
# 5 values linspaced between 0 & 10
c=np.linspace(0,10,5)
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
# array with zeros 

d=np.zeros((2,3))   # 2 rows 3 columns array with zeros

print("Array d:",d)

Array d: [[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# array of ones 

e=np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# An identity matrix is a special type of square matrix (same number of rows and columns) where:

# All the diagonal elements (from top-left to bottom-right) are 1s.

# All the off-diagonal elements are 0s.

# we can use identity or eye 

f=np.identity((5))
print(f)

g=np.eye((6))
print(("array g:", g))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
('array g:', array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]]))


# 2. Array Manipulation Functions

In [47]:
# Reshape an array 

a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print(reshaped)

[[1]
 [2]
 [3]]


In [51]:
# Flatten an array - np.ravel 

#flatten means doing straight whole array

data=np.array([[1,2,3],[4,5,6]])

a1=np.ravel(data)

print(a1)

[1 2 3 4 5 6]


In [53]:
# Transposing an array means flipping it over its diagonal, turning its rows into columns and columns into rows.

data=np.array([[1,2,3],[4,5,6]])

b1=np.transpose(data)
print(b1)

[[1 4]
 [2 5]
 [3 6]]


# 3. Mathematical Functions

In [56]:
# add two arrays 

a=np.array([1,2,3,4,])

added=np.add(a,2) # add 2 to each value 

print(added)

[3 4 5 6]


In [60]:
# squre each element

b=np.array([4,5,6,7])

square=np.power(b,2)

cube=np.power(b,3)

print(cube)
print(square)

[ 64 125 216 343]
[16 25 36 49]


In [62]:
# square root of each element 

a=np.array([4,5,6,7])

c=np.sqrt(a)

print(c)

[2.         2.23606798 2.44948974 2.64575131]


In [64]:
# dot product means multiplication and addition of values of same shaped arrays - np.dot

a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.dot(a,b) - # 4+10+18

print(c)


32


# 4. Statistical Functions

In [67]:
# mean of an array - np.mean

a=np.array([1,2,3,4])
mean=np.mean(a)

print(mean)

2.5


In [69]:
# standard deviation of an array - np.std

b=np.array([4,5,6,7])
SD=np.std(b)

print(SD)

1.118033988749895


In [ ]:
# Standard deviation is used because it tells you how spread out or clustered your data values are around 
# the mean (average). It’s one of the most important tools in statistics, data analysis, and research for
# understanding the variability in a dataset.

# A low standard deviation means data points are close to the mean → more consistent.

# A high standard deviation means data points are spread out → more variation.

# A low standard deviation means data points are close to the mean → more consistent.

# A high standard deviation means data points are spread out → more variation.

# 2. Easy Comparison Between Datasets
# You can compare how much variation exists in two or more datasets.

# Example: Compare exam scores of two classes. If both have the same average but one has a higher standard deviation,
# its scores are more spread out (less consistent).


In [71]:
b=np.array([4,5,6,7])
arr1=np.min(b)

print(arr1)

4


In [73]:
b=np.array([4,5,6,7])
c=np.max(b)
print(c)

7


## 5. Linear Algebra Functions

In [ ]:
# In Python, the determinant of a matrix is a scalar value that gives important information about the matrix.

# determinant - np.linlag.det
# INVERSE - np.linlag.inv

# Tells you if the matrix is invertible:

# If det(A) ≠ 0, the matrix has an inverse.

# If det(A) = 0, the matrix is singular (non-invertible).

In [86]:
data=np.array([[1,2],[4,5]])

a=np.linalg.det(data)
b=np.linalg.inv(data)

print(a)
print(b)


-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


## 6. Random Sampling Functions 

In [95]:
# 3 random values between 0 to 1

a=np.random.rand(3)

print(a)

[0.16391469 0.30329175 0.77503861]


In [97]:
b=np.random.randint(0,10,2) # size of 2 

print(b)

[8 9]


In [103]:
# seed refers to setting the starting point for generating random numbers. 
# This is important for creating repeatable (reproducible) results when using 
#functions from the random module or numpy.random.




import random

random.seed(42)   # Set the seed

print(random.randint(1, 100))

82


In [105]:
a=np.arange(0,10,2)

print(a)

[0 2 4 6 8]


#   7. Boolean & Logical Functions

In [108]:
# # Check if all elements are True  - np.all

a=np.array([True,False,True])

b=np.all(a)

print(b)

False


In [110]:
# check if all elements are true 

a=np.array([True,True,True])

b=np.all(a)

print(b)

True


In [112]:
# check if any are true - np.any 

a=np.array([True,False,False])

b=np.all(a)

print(b)

False


# 8. Set Operations

In [117]:
# Intersection of two arrays - np.intersect1d
# union - np.union1d

a=np.array([1,2,3,4])
b=np.array([4,5,6])

c=np.intersect1d(a,b)
print(c)

d=np.union1d(a,b)
print(d)

[4]
[1 2 3 4 5 6]


# 9. Array Attribute Functions

In [128]:
a=np.array([1,2,3])

b=a.shape
c=a.size
d=a.ndim
e=a.dtype

print(d)
print(b)
print(c)
print(e)

1
(3,)
3
int64


# 10. Other Functions

In [133]:
a=np.array([1,2,3])

b=np.copy(a)

print(b)


[1 2 3]


In [135]:
a=np.array([1,2,3])   #size in bytes 

b=a.nbytes

print(b)

24


In [139]:
a=np.array([1,2,3])  

c=np.shares_memory(a,b)

print(c)

False
